name: sign_flutter
description: Sign basic state management for Flutter.
version: 0.0.4
homepage: https://github.com/Mehmetyaz/sign_flutter
repository: https://github.com/Mehmetyaz/sign_flutter

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  sign: ^0.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
